---

- name: Include OS Family vars
  include_vars: "{{ansible_os_family}}.yml"
  tags: [ 'metricbeat' ] 

- include: install.yml
  become: true
  tags: [ 'metricbeat', 'metricbeat.install' ]

- include: config.yml
  become: true
  tags: [ 'metricbeat', 'metricbeat.config' ]

- include: template.yml
  become: true
  tags: [ 'metricbeat', 'metricbeat.template' ]

- include: dashboards.yml
  tags: [ 'metricbeat', 'metricbeat.dashboards' ]
  when: metricbeat_install_default_kibana_dashboards

- service:
    name: metricbeat
    enabled: yes
    state: started
  when: metricbeat_start_at_boot

# vi:ts=2:sw=2:et:ft=yaml
